name:
    pda
channels:
    - conda-forge
dependencies:
    - affogato
    - bioimageio.core
    - python-elf
    - python
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
    - torch_em
